#!/bin/bash

# script to calculate dN/dS gene by gene

# Required input in pwd: falserm_<clade>_<genename>_final_mask_align_NT.aln and correspondin nwk treefiles produced with excludeSpeciesTree.R, bppML.bpp parameter file, MapNH_model.bpp parameter file
# How parameters are edited in bppML.bpp file: DATA variable will be the name of the masked alignment; input.tree.file should be the treefile generated by iqtree and should have the same prefix of the aln file

for aln in falserm*NT.aln; do

gene=${aln%_final_mask_align_NT.aln}

sed "s/aln_filename/$aln/g" bppML.bpp > bppML_currentgene.bpp # make a temporary bppML file with the current gene alignment stored in the DATA variable

bppml param=bppML_currentgene.bpp # Fit a homogenous model with dN/dS over current gene for all branches

# Copy the parameters estimated by the model to MapNH.bpp file (in the $aln.ml_h.params.bpp output file) in the corresponding field

sed "s/aln_filename/$aln/g" MapNH_model.bpp > MapNH_model_currentgene.bpp
sed -i 's/curr_maptype/DnDs/g' MapNH_model_currentgene.bpp

# Run mapNH

mapnh param=MapNH_model_currentgene.bpp

rename 's/^/"${gene}"_/' CM_splitcounts_* # rename output files with gene alignment prefix

done

 